package com.aitogether.parentswb

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Medication
import androidx.compose.material.icons.filled.NoteAdd
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private val Purple600 = Color(0xFF8B5CF6)
private val WarmAmber = Color(0xFFF59E0B)
private val BG = Color(0xFFF5F0EB)
private val DarkGray = Color(0xFF4B5563)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MedicationPlanScreen(onBack: () -> Unit) {
    var selectedParent by remember { mutableStateOf("妈") }
    var medicationName by remember { mutableStateOf("降压药") }
    var frequency by remember { mutableStateOf("每天一次") }
    var morning by remember { mutableStateOf(true) }
    var evening by remember { mutableStateOf(true) }
    var noon by remember { mutableStateOf(false) }
    var planGenerated by remember { mutableStateOf(false) }
    var showToast by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("为爸妈添加用药计划", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "返回")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Purple600,
                    titleContentColor = Color.White,
                    navigationIconContentColor = Color.White
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(BG)
                .padding(padding)
                .padding(horizontal = 20.dp, vertical = 16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // 演示标签
            Text(
                text = "🎭 本页为演示功能，所有数据不会被保存",
                fontSize = 13.sp,
                color = DarkGray,
                modifier = Modifier.padding(bottom = 4.dp)
            )

            // 父母选择
            Text("选择父母", fontWeight = FontWeight.SemiBold, fontSize = 16.sp)
            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                listOf("妈", "爸").forEach { parent ->
                    Button(
                        onClick = { selectedParent = parent },
                        colors = ButtonDefaults.buttonColors(
                            containerColor = if (selectedParent == parent) Purple600 else Color(0xFFE5E7EB)
                        ),
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Text(
                            parent,
                            color = if (selectedParent == parent) Color.White else DarkGray,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                }
            }

            // 药名
            OutlinedTextField(
                value = medicationName,
                onValueChange = { medicationName = it },
                label = { Text("药名") },
                leadingIcon = { Icon(Icons.Filled.Medication, contentDescription = null, tint = Purple600) },
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp)
            )

            // 频率
            Text("用药频率", fontWeight = FontWeight.SemiBold, fontSize = 16.sp)
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf("每天一次", "每天两次", "自定义").forEach { freq ->
                    Button(
                        onClick = { frequency = freq },
                        colors = ButtonDefaults.buttonColors(
                            containerColor = if (frequency == freq) Purple600 else Color(0xFFE5E7EB)
                        ),
                        shape = RoundedCornerShape(8.dp)
                    ) {
                        Text(
                            freq,
                            fontSize = 13.sp,
                            color = if (frequency == freq) Color.White else DarkGray
                        )
                    }
                }
            }

            // 时间选择
            Text("用药时间", fontWeight = FontWeight.SemiBold, fontSize = 16.sp)
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                TimeChip("早上", morning) { morning = it }
                TimeChip("中午", noon) { noon = it }
                TimeChip("晚上", evening) { evening = it }
            }

            Spacer(modifier = Modifier.height(4.dp))

            // 生成按钮
            Button(
                onClick = {
                    planGenerated = true
                    showToast = true
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(52.dp),
                colors = ButtonDefaults.buttonColors(containerColor = Purple600),
                shape = RoundedCornerShape(12.dp)
            ) {
                Icon(Icons.Filled.NoteAdd, contentDescription = null, tint = Color.White)
                Spacer(modifier = Modifier.width(8.dp))
                Text("生成本周示例计划", fontSize = 16.sp, fontWeight = FontWeight.SemiBold, color = Color.White)
            }

            // Toast 提示
            if (showToast) {
                Card(
                    colors = CardDefaults.cardColors(containerColor = Color(0xFFF0F9FF)),
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text(
                        text = "✅ 已为「$selectedParent · $medicationName」生成本周示例计划（仅用于演示，不会保存）。",
                        fontSize = 14.sp,
                        modifier = Modifier.padding(12.dp),
                        color = DarkGray
                    )
                }
            }

            // 计划预览
            if (planGenerated) {
                PlanPreview(
                    parent = selectedParent,
                    med = medicationName,
                    morning = morning,
                    noon = noon,
                    evening = evening
                )
            }
        }
    }
}

@Composable
private fun TimeChip(label: String, selected: Boolean, onToggle: (Boolean) -> Unit) {
    Button(
        onClick = { onToggle(!selected) },
        colors = ButtonDefaults.buttonColors(
            containerColor = if (selected) Purple600 else Color(0xFFE5E7EB)
        ),
        shape = RoundedCornerShape(8.dp),
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp)
    ) {
        Text(
            label,
            fontSize = 14.sp,
            color = if (selected) Color.White else DarkGray
        )
    }
}

@Composable
private fun PlanPreview(parent: String, med: String, morning: Boolean, noon: Boolean, evening: Boolean) {
    val times = buildList {
        if (morning) add("早上")
        if (noon) add("中午")
        if (evening) add("晚上")
    }
    val days = listOf("周一", "周二", "周三", "周四", "周五", "周六", "周日")

    Card(
        colors = CardDefaults.cardColors(containerColor = Color.White),
        shape = RoundedCornerShape(12.dp),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(Icons.Filled.CheckCircle, contentDescription = null, tint = Purple600, modifier = Modifier.size(20.dp))
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = "$parent · $med · ${times.joinToString("、")}用药计划预览",
                    fontWeight = FontWeight.SemiBold,
                    fontSize = 15.sp
                )
            }
            Spacer(modifier = Modifier.height(12.dp))

            days.forEach { day ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text(day, fontWeight = FontWeight.Medium, fontSize = 14.sp, color = DarkGray)
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        times.forEach { time ->
                            Surface(
                                color = Color(0xFFF0F9FF),
                                shape = RoundedCornerShape(6.dp)
                            ) {
                                Text(
                                    "$time · $med",
                                    fontSize = 12.sp,
                                    color = Color(0xFF1E40AF),
                                    modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp)
                                )
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(12.dp))
            Text(
                text = "本页面仅用于展示用药计划添加流程，所有数据不会被保存或上传。",
                fontSize = 11.sp,
                color = Color(0xFF9CA3AF)
            )
        }
    }
}
